_target_: sat_pred.training_module.TrainingModule
model: 
  _target_: sat_pred.models.simvp_model.SimVP
  num_channels: 11
  history_len: 12
  forecast_len: 12
optimizer:
  _target_: sat_pred.optimizers.AdamWReduceLROnPlateau
  lr: 0.0005
target_loss: MAE

