_target_: cloudcasting.dataset.SatelliteDataModule
zarr_path: 
  - /mnt/disks/sat_data/2019_training_nonhrv.zarr
  - /mnt/disks/sat_data/2020_training_nonhrv.zarr
  - /mnt/disks/sat_data/2021_training_nonhrv.zarr
  - /mnt/disks/sat_data/2022_training_nonhrv.zarr
history_mins: 165
forecast_mins: 180
sample_freq_mins: 15
train_period: ["2019-01-01 00:00", "2021-12-31 23:55"]
val_period: ["2022-01-01 00:00", "2022-12-31 23:55"]
num_workers: 6
prefetch_factor: 2
batch_size: 1
nan_to_num: true
pin_memory: false
persistent_workers: true